[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "forestgeom"
version = "0.0.1"
description = "Forest kernel package"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "GPL-3.0-or-later" }
authors = [
	{ name = "Jake Rhodes", email = "jakerhodes8@gmail.com" },
	{ name = "Adrien Aumon", email = "adrien.aumon@umontreal.ca" },
]
urls = { "Homepage" = "https://github.com/jakerhodes/RF-GAP-Python" }

dependencies = [
	"numpy",
	"scipy",
	"scikit-learn",
]

[project.optional-dependencies]
boosted = ["lightgbm", "xgboost"]
viz = ["matplotlib", "seaborn", "umap-learn"]
experiments = ["pandas", "pyarrow", "matplotlib", "seaborn", "umap-learn"]
test = ["pytest", "pytest-cov"]
all = ["lightgbm","xgboost","matplotlib","seaborn","umap-learn","pandas","pyarrow","pytest","pytest-cov"]

[tool.setuptools]
package-dir = { "" = "src" }
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["forestgeom*"]
